// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package user

import (
	"database/sql"
)

type Profile struct {
	ID        int64
	FirstName sql.NullString
	LastName  sql.NullString
	Address   sql.NullString
}

type User struct {
	ID                int64
	Email             string
	Password          string
	PhoneNumber       string
	Otp               sql.NullString
	OtpExpirationTime sql.NullTime
	ProfileID         sql.NullInt32
}
