// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package user

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Profile struct {
	ID        int64
	FirstName pgtype.Text
	LastName  pgtype.Text
	Address   pgtype.Text
}

type User struct {
	ID                int64
	Email             string
	Password          string
	PhoneNumber       string
	Otp               pgtype.Text
	OtpExpirationTime pgtype.Timestamp
	ProfileID         pgtype.Int4
}
